# Generated by Django 3.1.2 on 2020-10-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='designer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='developer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
