# Generated by Django 3.1.2 on 2020-10-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201020_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
