# Generated by Django 3.1.2 on 2020-10-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201018_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='developer',
            field=models.BooleanField(default=False),
        ),
    ]
