# Generated by Django 3.1.2 on 2020-10-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20201019_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='application_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
