# Generated by Django 3.1.2 on 2020-10-19 19:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20201019_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='country',
            field=django_countries.fields.CountryField(default='NZ', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='designer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='developer',
            field=models.BooleanField(default=False),
        ),
    ]
