# Generated by Django 3.1.2 on 2020-10-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20201019_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
