# Generated by Django 3.1.2 on 2020-10-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20201020_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
