# Generated by Django 3.1.2 on 2020-10-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
