# Generated by Django 3.1.2 on 2020-11-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_salary_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='salary_range',
            field=models.CharField(blank=True, help_text='Test', max_length=100),
        ),
    ]
