# Generated by Django 3.1.2 on 2020-11-01 21:23

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_auto_20201101_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='how_to_apply',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='application_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Application URL'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_info',
            field=models.CharField(blank=True, help_text='This email is public. The apply button defaults to it if you do not supply an Apply Url', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Developer', 'Developer'), ('Designer', 'Designer'), ('DevOps', 'DevOps')], help_text='This will dictate who gets shown what posts, as well as in searches', max_length=200, verbose_name='Role Type'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='salary_range',
            field=models.CharField(blank=True, help_text='Ex: $70,000 - $80,000', max_length=100, verbose_name='Annual Salary'),
        ),
    ]
