# Generated by Django 3.1.2 on 2020-11-01 21:29

import ckeditor.fields
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20201101_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='experience',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Junior', 'Junior'), ('Intermediate', 'Intermediate'), ('Senior', 'Senior'), ('Intern', 'Intern')], help_text='You can select more than one', max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='how_to_apply',
            field=ckeditor.fields.RichTextField(verbose_name='How To Apply?'),
        ),
    ]
